# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Import additional configuration files
#
# Imports are loaded in order, skipping all missing files, with the importing
# file being loaded last. If a field is already present in a previous import, it
# will be replaced.
#
# All imports must either be absolute paths starting with `/`, or paths relative
# to the user's home directory starting with `~/`.
import:
  - ~/.config/alacritty/themes/nord.yml

env:
  WINIT_X11_SCALE_FACTOR: "1"

window:
  # Window dimensions (changes require restart)
  #
  # Number of lines/columns (not pixels) in the terminal. The number of columns
  # must be at least `2`, while using a value of `0` for columns and lines will
  # fall back to the window manager's recommended size.
  dimensions:
    columns: 120
    lines: 40

    # dimensions for laptop only
    # columns: 86
    # lines: 25

  padding:
    x: 2
    y: 1

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 5000

# Font configuration
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    family: Hack

  # Point size
  size: 14.0

cursor:
  # Cursor style
  style:
    # Cursor shape
    #
    # Values for `shape`:
    #   - ▇ Block
    #   - _ Underline
    #   - | Beam
    shape: Block

    # Cursor blinking state
    #
    # Values for `blinking`:
    #   - Never: Prevent the cursor from ever blinking
    #   - Off: Disable blinking by default
    #   - On: Enable blinking by default
    #   - Always: Force the cursor to always blink
    blinking: On

  # Cursor blinking interval in milliseconds.
  blink_interval: 500

  # Thickness of the cursor relative to the cell width as floating point number
  # from `0.0` to `1.0`.
  thickness: 0.10

# Shell
#
# You can set `shell.program` to the path of your favorite shell, e.g.
# `/bin/fish`. Entries in `shell.args` are passed unmodified as arguments to the
# shell.
shell:
  program: /bin/fish
  args:
    - -l
    - -i
    #- -c
    #- zellij --layout-path ~/.config/zellij/layout.yaml

mouse:
  hide_when_typing: true

  hints:
    # URL modifiers
    #
    # These are the modifiers that need to be held down for opening URLs when
    # clicking on them.
    modifiers: Control

# Mouse bindings
mouse_bindings:
  - { mouse: Right, action: Paste }
  - { mouse: Middle, action: PasteSelection }

# Key bindings
key_bindings:
  - { key: F11, action: ToggleFullscreen }
  - { key: T, mods: Control|Shift, action: SpawnNewInstance }
