import = ["/home/gabriele/.config/alacritty/themes/nord.toml"]

[cursor]
blink_interval = 500
thickness = 0.1

[cursor.style]
blinking = "On"
shape = "Block"

[env]
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 12.0

[font.normal]
family = "Hack"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "Paste"
mouse = "Right"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

# [mouse.hints]
# modifiers = "Control"

[scrolling]
history = 5000

[shell]
args = [
    "-l",
    "-c",
    "zellij --layout ~/.config/zellij/layout.kdl attach --index 0 --create",
]
program = "/bin/fish"

[window.dimensions]
columns = 110
lines = 40

[window.padding]
x = 2
y = 1
