---
keybinds:
    normal:    
        - unbind: true
        - action: [ NewPane: Right, ]
          key: [ Alt: ']',]
        - action: [ NewPane: Down, ]
          key: [ Alt: '[',]
        - action: [ NewPane: , ]
          key: [ Alt: 'n',]
        - action: [ NewTab: ,]
          key: [ Ctrl: 'n', ]
        - action: [MoveFocusOrTab: Left,]
          key: [ Ctrl: 'k', ]
        - action: [MoveFocusOrTab: Right,]
          key: [ Ctrl: 'o',]
